"""
Property-based tests for configuration loading.

Feature: kia-paint-shop-iot-prototype
Property 1: Valores generados dentro de rangos válidos

Tests that all values generated by the simulator are within the defined ranges
for each variable (min_range, max_range).

Validates: Requirements 1.2
"""

import sys
from pathlib import Path

# Add simulator to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "simulator"))

from hypothesis import given, strategies as st, settings
import pytest
from config_loader import ConfigLoader, Variable


# Feature: kia-paint-shop-iot-prototype, Property 1: Valores generados dentro de rangos válidos
@settings(max_examples=20)
@given(
    min_range=st.floats(min_value=0.0, max_value=100.0, allow_nan=False, allow_infinity=False),
    max_range=st.floats(min_value=100.1, max_value=1000.0, allow_nan=False, allow_infinity=False),
)
def test_property_1_variable_ranges_are_valid(min_range, max_range):
    """
    Property 1: Para cualquier variable con rangos definidos (min_range, max_range),
    los rangos deben ser válidos (min < max) y los umbrales de alarma deben estar
    dentro de esos rangos.
    
    **Validates: Requirements 1.2**
    """
    # Calculate alarm thresholds (10% from edges)
    range_span = max_range - min_range
    alarm_low = min_range + (range_span * 0.1)
    alarm_high = max_range - (range_span * 0.1)
    
    # Create a variable with these ranges
    variable = Variable(
        variable_id="TEST-001",
        name="Test Variable",
        area="pre-treatment",
        unit="test",
        min_range=min_range,
        max_range=max_range,
        alarm_low=alarm_low,
        alarm_high=alarm_high,
        description="Test variable",
        source_file="test",
        active=True
    )
    
    # Validate the variable
    is_valid, error_msg = variable.validate()
    
    # Property: Variable should always be valid when properly constructed
    assert is_valid, f"Variable validation failed: {error_msg}"
    
    # Property: min_range must be less than max_range
    assert variable.min_range < variable.max_range, \
        f"min_range ({variable.min_range}) must be < max_range ({variable.max_range})"
    
    # Property: alarm_low must be within range
    assert variable.min_range <= variable.alarm_low <= variable.max_range, \
        f"alarm_low ({variable.alarm_low}) must be within [{variable.min_range}, {variable.max_range}]"
    
    # Property: alarm_high must be within range
    assert variable.min_range <= variable.alarm_high <= variable.max_range, \
        f"alarm_high ({variable.alarm_high}) must be within [{variable.min_range}, {variable.max_range}]"
    
    # Property: alarm_low must be less than alarm_high
    assert variable.alarm_low < variable.alarm_high, \
        f"alarm_low ({variable.alarm_low}) must be < alarm_high ({variable.alarm_high})"


def test_property_1_loaded_variables_have_valid_ranges():
    """
    Property 1: Para cualquier variable cargada desde CSV, todos los rangos
    deben ser válidos y los valores de alarma deben estar dentro de los rangos.
    
    **Validates: Requirements 1.2**
    """
    # Load all variables from CSV files
    loader = ConfigLoader(base_path=Path(__file__).parent.parent.parent / "simulator")
    
    try:
        variables = loader.load_all()
    except FileNotFoundError:
        pytest.skip("CSV files not found - skipping test")
        return
    
    # Property: All loaded variables must have valid ranges
    for var_id, variable in variables.items():
        # Check min < max
        assert variable.min_range < variable.max_range, \
            f"{var_id}: min_range ({variable.min_range}) must be < max_range ({variable.max_range})"
        
        # Check alarm thresholds are within range
        assert variable.min_range <= variable.alarm_low <= variable.max_range, \
            f"{var_id}: alarm_low ({variable.alarm_low}) must be within [{variable.min_range}, {variable.max_range}]"
        
        assert variable.min_range <= variable.alarm_high <= variable.max_range, \
            f"{var_id}: alarm_high ({variable.alarm_high}) must be within [{variable.min_range}, {variable.max_range}]"
        
        # Check alarm_low < alarm_high
        assert variable.alarm_low < variable.alarm_high, \
            f"{var_id}: alarm_low ({variable.alarm_low}) must be < alarm_high ({variable.alarm_high})"
        
        # Check area is valid
        assert variable.area in ['pre-treatment', 'e-coat', 'production-control'], \
            f"{var_id}: area must be one of: pre-treatment, e-coat, production-control"
        
        # Check required fields are not empty
        assert variable.variable_id, f"{var_id}: variable_id cannot be empty"
        assert variable.name, f"{var_id}: name cannot be empty"


def test_property_1_variable_count_is_consistent():
    """
    Property 1: El número total de variables cargadas debe ser consistente
    con las especificaciones (aproximadamente 100 variables).
    
    **Validates: Requirements 1.1**
    """
    loader = ConfigLoader(base_path=Path(__file__).parent.parent.parent / "simulator")
    
    try:
        variables = loader.load_all()
    except FileNotFoundError:
        pytest.skip("CSV files not found - skipping test")
        return
    
    # Property: Total variables should be around 100 (allowing some variance)
    total_vars = len(variables)
    assert 90 <= total_vars <= 110, \
        f"Expected ~100 variables, got {total_vars}"
    
    # Property: Each area should have the expected number of variables
    pt_vars = loader.get_variables_by_area('pre-treatment')
    ed_vars = loader.get_variables_by_area('e-coat')
    pc_vars = loader.get_variables_by_area('production-control')
    
    # Pre-Treatment: ~48 variables (allowing some variance)
    assert 40 <= len(pt_vars) <= 50, \
        f"Expected ~48 Pre-Treatment variables, got {len(pt_vars)}"
    
    # E-Coat: ~18 variables (allowing some variance)
    assert 15 <= len(ed_vars) <= 25, \
        f"Expected ~18 E-Coat variables, got {len(ed_vars)}"
    
    # Production Control: 34 variables (exact)
    assert len(pc_vars) == 34, \
        f"Expected 34 Production Control variables, got {len(pc_vars)}"


@settings(max_examples=20)
@given(
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control'])
)
def test_property_1_variables_by_area_are_consistent(area):
    """
    Property 1: Todas las variables de un área específica deben tener
    el campo 'area' correcto.
    
    **Validates: Requirements 1.1**
    """
    loader = ConfigLoader(base_path=Path(__file__).parent.parent.parent / "simulator")
    
    try:
        loader.load_all()
    except FileNotFoundError:
        pytest.skip("CSV files not found - skipping test")
        return
    
    # Get variables for the specified area
    area_vars = loader.get_variables_by_area(area)
    
    # Property: All variables in the list must have the correct area
    for variable in area_vars:
        assert variable.area == area, \
            f"Variable {variable.variable_id} has area '{variable.area}', expected '{area}'"


def test_property_1_active_variables_are_all_active():
    """
    Property 1: Todas las variables retornadas por get_active_variables()
    deben tener active=True.
    
    **Validates: Requirements 1.1**
    """
    loader = ConfigLoader(base_path=Path(__file__).parent.parent.parent / "simulator")
    
    try:
        loader.load_all()
    except FileNotFoundError:
        pytest.skip("CSV files not found - skipping test")
        return
    
    # Get active variables
    active_vars = loader.get_active_variables()
    
    # Property: All variables in the list must be active
    for variable in active_vars:
        assert variable.active is True, \
            f"Variable {variable.variable_id} is not active but was returned by get_active_variables()"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
