"""
Property-based tests for alarm persistence.

Feature: kia-paint-shop-iot-prototype
Property 11: Persistencia de alarmas generadas

Tests that alarms generated by threshold exceedance are properly persisted
in DynamoDB with all required fields.

Validates: Requirements 4.3
"""

import sys
import json
from pathlib import Path
from datetime import datetime
from unittest.mock import Mock, MagicMock, patch
from typing import Dict, Any

# Add lambdas to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "lambdas" / "process"))

from hypothesis import given, strategies as st, settings, assume
import pytest

from handler import handler, create_alarm_record, store_alarm
from anomaly_detector import AnomalyDetector, AlarmSeverity, AlarmResult


# Feature: kia-paint-shop-iot-prototype, Property 11: Persistencia de alarmas generadas
@settings(max_examples=100)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
    alarm_low=st.floats(min_value=10.0, max_value=50.0, allow_nan=False, allow_infinity=False),
    alarm_high=st.floats(min_value=100.0, max_value=200.0, allow_nan=False, allow_infinity=False),
    severity=st.sampled_from([AlarmSeverity.WARNING, AlarmSeverity.CRITICAL])
)
def test_property_11_alarm_record_contains_all_required_fields(
    variable_id, area, value, alarm_low, alarm_high, severity
):
    """
    Property 11: Para cualquier alarma generada por exceso de umbrales,
    debe existir un registro con todos los campos requeridos:
    alarm_id, variable_id, severity, status=active, value, threshold, created_at.
    
    **Validates: Requirements 4.3**
    """
    # Create alarm result
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=severity,
        threshold_type="high",
        threshold_value=alarm_high,
        exceedance_percent=15.0,
        message=f"Test alarm for {variable_id}",
        value=value
    )
    
    # Create alarm record
    timestamp = "2024-01-15T10:30:00.000Z"
    alarm_item = create_alarm_record(
        variable_id=variable_id,
        area=area,
        alarm_result=alarm_result,
        timestamp=timestamp,
        variable_name=f"Test Variable {variable_id}"
    )
    
    # Property: All required fields must be present
    required_fields = [
        'alarm_id', 'variable_id', 'severity', 'status', 
        'value', 'threshold', 'created_at'
    ]
    
    for field in required_fields:
        assert field in alarm_item, f"Alarm record missing required field: {field}"
    
    # Property: Fields must have correct types and values
    assert isinstance(alarm_item['alarm_id'], str), "alarm_id must be string"
    assert len(alarm_item['alarm_id']) > 0, "alarm_id must not be empty"
    
    assert alarm_item['variable_id'] == variable_id, \
        f"variable_id mismatch: expected {variable_id}, got {alarm_item['variable_id']}"
    
    assert alarm_item['severity'] == severity.value, \
        f"severity mismatch: expected {severity.value}, got {alarm_item['severity']}"
    
    assert alarm_item['status'] == 'active', \
        f"status must be 'active', got {alarm_item['status']}"
    
    assert alarm_item['value'] == value, \
        f"value mismatch: expected {value}, got {alarm_item['value']}"
    
    assert alarm_item['threshold'] == alarm_high, \
        f"threshold mismatch: expected {alarm_high}, got {alarm_item['threshold']}"
    
    assert isinstance(alarm_item['created_at'], str), "created_at must be string"
    assert len(alarm_item['created_at']) > 0, "created_at must not be empty"


@settings(max_examples=100)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
)
def test_property_11_alarm_id_is_unique(variable_id, area, value):
    """
    Property 11: Para cualquier alarma generada, el alarm_id debe ser único (UUID).
    
    **Validates: Requirements 4.3**
    """
    # Create multiple alarm records for the same variable
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=AlarmSeverity.WARNING,
        threshold_type="high",
        threshold_value=100.0,
        exceedance_percent=5.0,
        message=f"Test alarm",
        value=value
    )
    
    timestamp = "2024-01-15T10:30:00.000Z"
    
    # Generate multiple alarm records
    alarm_ids = set()
    for _ in range(10):
        alarm_item = create_alarm_record(
            variable_id=variable_id,
            area=area,
            alarm_result=alarm_result,
            timestamp=timestamp
        )
        alarm_ids.add(alarm_item['alarm_id'])
    
    # Property: All alarm_ids must be unique
    assert len(alarm_ids) == 10, \
        f"Expected 10 unique alarm_ids, got {len(alarm_ids)}"
    
    # Property: Each alarm_id should be a valid UUID format
    import re
    uuid_pattern = re.compile(
        r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
        re.IGNORECASE
    )
    
    for alarm_id in alarm_ids:
        assert uuid_pattern.match(alarm_id), \
            f"alarm_id '{alarm_id}' is not a valid UUID"


@settings(max_examples=100)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
)
def test_property_11_alarm_status_defaults_to_active(variable_id, area, value):
    """
    Property 11: Para cualquier alarma recién generada, el status debe ser 'active'.
    
    **Validates: Requirements 4.3**
    """
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=AlarmSeverity.CRITICAL,
        threshold_type="low",
        threshold_value=10.0,
        exceedance_percent=20.0,
        message=f"Test alarm",
        value=value
    )
    
    timestamp = "2024-01-15T10:30:00.000Z"
    alarm_item = create_alarm_record(
        variable_id=variable_id,
        area=area,
        alarm_result=alarm_result,
        timestamp=timestamp
    )
    
    # Property: Status must be 'active'
    assert alarm_item['status'] == 'active', \
        f"New alarm status must be 'active', got '{alarm_item['status']}'"


@settings(max_examples=100)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
)
def test_property_11_created_at_is_valid_iso8601(variable_id, area, value):
    """
    Property 11: Para cualquier alarma generada, el campo created_at debe ser
    un timestamp válido en formato ISO 8601.
    
    **Validates: Requirements 4.3**
    """
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=AlarmSeverity.WARNING,
        threshold_type="high",
        threshold_value=100.0,
        exceedance_percent=8.0,
        message=f"Test alarm",
        value=value
    )
    
    timestamp = "2024-01-15T10:30:00.000Z"
    alarm_item = create_alarm_record(
        variable_id=variable_id,
        area=area,
        alarm_result=alarm_result,
        timestamp=timestamp
    )
    
    # Property: created_at must be parseable as ISO 8601
    created_at = alarm_item['created_at']
    
    try:
        parsed_time = datetime.fromisoformat(created_at.replace('Z', '+00:00'))
        assert parsed_time is not None, "Failed to parse created_at timestamp"
    except (ValueError, AttributeError) as e:
        pytest.fail(f"created_at '{created_at}' is not valid ISO 8601: {e}")
    
    # Property: created_at should be recent (within last minute)
    from datetime import timezone
    now = datetime.now(timezone.utc)
    time_diff = abs((now - parsed_time).total_seconds())
    
    assert time_diff < 60, \
        f"created_at timestamp is not recent: {time_diff}s ago"


@settings(max_examples=100)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
    threshold_type=st.sampled_from(['low', 'high'])
)
def test_property_11_alarm_contains_threshold_information(
    variable_id, area, value, threshold_type
):
    """
    Property 11: Para cualquier alarma generada, debe contener información
    completa del umbral: threshold, threshold_type, exceedance_percent.
    
    **Validates: Requirements 4.3**
    """
    threshold_value = 50.0 if threshold_type == 'low' else 150.0
    exceedance = 12.5
    
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=AlarmSeverity.CRITICAL,
        threshold_type=threshold_type,
        threshold_value=threshold_value,
        exceedance_percent=exceedance,
        message=f"Test alarm",
        value=value
    )
    
    timestamp = "2024-01-15T10:30:00.000Z"
    alarm_item = create_alarm_record(
        variable_id=variable_id,
        area=area,
        alarm_result=alarm_result,
        timestamp=timestamp
    )
    
    # Property: Threshold information must be present
    assert 'threshold' in alarm_item, "Alarm missing 'threshold' field"
    assert 'threshold_type' in alarm_item, "Alarm missing 'threshold_type' field"
    assert 'exceedance_percent' in alarm_item, "Alarm missing 'exceedance_percent' field"
    
    # Property: Values must match alarm_result
    assert alarm_item['threshold'] == threshold_value, \
        f"threshold mismatch: expected {threshold_value}, got {alarm_item['threshold']}"
    
    assert alarm_item['threshold_type'] == threshold_type, \
        f"threshold_type mismatch: expected {threshold_type}, got {alarm_item['threshold_type']}"
    
    assert alarm_item['exceedance_percent'] == round(exceedance, 2), \
        f"exceedance_percent mismatch: expected {round(exceedance, 2)}, got {alarm_item['exceedance_percent']}"


@settings(max_examples=100)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
)
def test_property_11_alarm_contains_message(variable_id, area, value):
    """
    Property 11: Para cualquier alarma generada, debe contener un mensaje
    descriptivo no vacío.
    
    **Validates: Requirements 4.3**
    """
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=AlarmSeverity.WARNING,
        threshold_type="high",
        threshold_value=100.0,
        exceedance_percent=5.0,
        message=f"Variable {variable_id} exceeded threshold",
        value=value
    )
    
    timestamp = "2024-01-15T10:30:00.000Z"
    alarm_item = create_alarm_record(
        variable_id=variable_id,
        area=area,
        alarm_result=alarm_result,
        timestamp=timestamp
    )
    
    # Property: Message must be present and non-empty
    assert 'message' in alarm_item, "Alarm missing 'message' field"
    assert isinstance(alarm_item['message'], str), "Message must be string"
    assert len(alarm_item['message']) > 0, "Message must not be empty"


@settings(max_examples=100)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
)
def test_property_11_alarm_pk_sk_structure(variable_id, area, value):
    """
    Property 11: Para cualquier alarma almacenada en DynamoDB, debe tener
    estructura de keys: PK="ALARM#{alarm_id}", SK="METADATA".
    
    **Validates: Requirements 4.3**
    """
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=AlarmSeverity.CRITICAL,
        threshold_type="low",
        threshold_value=10.0,
        exceedance_percent=15.0,
        message=f"Test alarm",
        value=value
    )
    
    timestamp = "2024-01-15T10:30:00.000Z"
    alarm_item = create_alarm_record(
        variable_id=variable_id,
        area=area,
        alarm_result=alarm_result,
        timestamp=timestamp
    )
    
    # Property: PK and SK must be present
    assert 'PK' in alarm_item, "Alarm missing 'PK' field"
    assert 'SK' in alarm_item, "Alarm missing 'SK' field"
    
    # Property: PK must have format "ALARM#{alarm_id}"
    pk = alarm_item['PK']
    assert pk.startswith('ALARM#'), f"PK must start with 'ALARM#', got '{pk}'"
    
    pk_parts = pk.split('#')
    assert len(pk_parts) == 2, f"PK must have format 'ALARM#{{alarm_id}}', got '{pk}'"
    assert pk_parts[0] == 'ALARM', f"PK prefix must be 'ALARM', got '{pk_parts[0]}'"
    assert len(pk_parts[1]) > 0, "alarm_id in PK must not be empty"
    
    # Property: SK must be "METADATA"
    assert alarm_item['SK'] == 'METADATA', \
        f"SK must be 'METADATA', got '{alarm_item['SK']}'"
    
    # Property: alarm_id in PK must match alarm_id field
    alarm_id_from_pk = pk_parts[1]
    assert alarm_id_from_pk == alarm_item['alarm_id'], \
        f"alarm_id in PK '{alarm_id_from_pk}' must match alarm_id field '{alarm_item['alarm_id']}'"


@settings(max_examples=100)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
)
def test_property_11_alarm_preserves_area_information(variable_id, area, value):
    """
    Property 11: Para cualquier alarma generada, debe preservar la información
    del área de la variable.
    
    **Validates: Requirements 4.3**
    """
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=AlarmSeverity.WARNING,
        threshold_type="high",
        threshold_value=100.0,
        exceedance_percent=7.0,
        message=f"Test alarm",
        value=value
    )
    
    timestamp = "2024-01-15T10:30:00.000Z"
    alarm_item = create_alarm_record(
        variable_id=variable_id,
        area=area,
        alarm_result=alarm_result,
        timestamp=timestamp
    )
    
    # Property: Area must be preserved
    assert 'area' in alarm_item, "Alarm missing 'area' field"
    assert alarm_item['area'] == area, \
        f"area mismatch: expected '{area}', got '{alarm_item['area']}'"


@settings(max_examples=100)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
)
def test_property_11_alarm_includes_sensor_timestamp(variable_id, area, value):
    """
    Property 11: Para cualquier alarma generada, debe incluir el timestamp
    del sensor que generó la lectura que causó la alarma.
    
    **Validates: Requirements 4.3**
    """
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=AlarmSeverity.CRITICAL,
        threshold_type="high",
        threshold_value=150.0,
        exceedance_percent=18.0,
        message=f"Test alarm",
        value=value
    )
    
    sensor_timestamp = "2024-01-15T10:30:00.000Z"
    alarm_item = create_alarm_record(
        variable_id=variable_id,
        area=area,
        alarm_result=alarm_result,
        timestamp=sensor_timestamp
    )
    
    # Property: Sensor timestamp must be preserved
    assert 'sensor_timestamp' in alarm_item, "Alarm missing 'sensor_timestamp' field"
    assert alarm_item['sensor_timestamp'] == sensor_timestamp, \
        f"sensor_timestamp mismatch: expected '{sensor_timestamp}', got '{alarm_item['sensor_timestamp']}'"


@settings(max_examples=50)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=0.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
    alarm_low=st.floats(min_value=10.0, max_value=50.0, allow_nan=False, allow_infinity=False),
    alarm_high=st.floats(min_value=100.0, max_value=200.0, allow_nan=False, allow_infinity=False),
)
@patch('handler.alarms_table')
def test_property_11_store_alarm_calls_dynamodb(
    mock_table, variable_id, area, value, alarm_low, alarm_high
):
    """
    Property 11: Para cualquier alarma generada, la función store_alarm
    debe invocar DynamoDB put_item con el item correcto.
    
    **Validates: Requirements 4.3**
    """
    # Create alarm result
    alarm_result = AlarmResult(
        is_alarm=True,
        severity=AlarmSeverity.WARNING,
        threshold_type="high",
        threshold_value=alarm_high,
        exceedance_percent=5.0,
        message=f"Test alarm",
        value=value
    )
    
    timestamp = "2024-01-15T10:30:00.000Z"
    alarm_item = create_alarm_record(
        variable_id=variable_id,
        area=area,
        alarm_result=alarm_result,
        timestamp=timestamp
    )
    
    # Mock DynamoDB table
    mock_table.put_item = MagicMock(return_value={})
    
    # Store alarm
    result = store_alarm(alarm_item)
    
    # Property: store_alarm must return True on success
    assert result is True, "store_alarm should return True on success"
    
    # Property: put_item must be called exactly once
    assert mock_table.put_item.call_count == 1, \
        f"put_item should be called once, was called {mock_table.put_item.call_count} times"
    
    # Property: put_item must be called with the alarm_item
    call_args = mock_table.put_item.call_args
    assert call_args is not None, "put_item was not called"
    assert 'Item' in call_args.kwargs, "put_item must be called with Item parameter"
    
    stored_item = call_args.kwargs['Item']
    assert stored_item == alarm_item, \
        f"put_item called with wrong item"


@settings(max_examples=50)
@given(
    variable_id=st.text(
        min_size=1, 
        max_size=50, 
        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_'
    ).filter(lambda x: x and x.strip()),
    area=st.sampled_from(['pre-treatment', 'e-coat', 'production-control']),
    value=st.floats(min_value=200.0, max_value=1000.0, allow_nan=False, allow_infinity=False),
    alarm_low=st.floats(min_value=10.0, max_value=50.0, allow_nan=False, allow_infinity=False),
    alarm_high=st.floats(min_value=100.0, max_value=150.0, allow_nan=False, allow_infinity=False),
)
@patch('handler.cloudwatch')
@patch('handler.alarms_table')
@patch('handler.variables_table')
def test_property_11_handler_creates_alarm_for_threshold_violation(
    mock_variables_table, mock_alarms_table, mock_cloudwatch,
    variable_id, area, value, alarm_low, alarm_high
):
    """
    Property 11: Para cualquier evento con valor que excede umbrales,
    el handler debe crear un registro de alarma en DynamoDB.
    
    **Validates: Requirements 4.3**
    """
    # Ensure value exceeds high threshold
    assume(value > alarm_high)
    
    # Mock variable metadata
    mock_variables_table.get_item = MagicMock(return_value={
        'Item': {
            'PK': f'VAR#{variable_id}',
            'SK': 'METADATA',
            'variable_id': variable_id,
            'name': f'Test Variable {variable_id}',
            'area': area,
            'alarm_low': alarm_low,
            'alarm_high': alarm_high,
            'min_range': 0.0,
            'max_range': 1000.0
        }
    })
    
    # Mock DynamoDB alarms table
    mock_alarms_table.put_item = MagicMock(return_value={})
    
    # Mock CloudWatch
    mock_cloudwatch.put_metric_data = MagicMock(return_value={})
    
    # Create event
    event = {
        'detail': {
            'variable_id': variable_id,
            'area': area,
            'value': value,
            'timestamp': '2024-01-15T10:30:00.000Z',
            'unit': 'test'
        }
    }
    
    # Create mock context
    context = Mock()
    context.request_id = 'test-request-123'
    
    # Call handler
    response = handler(event, context)
    
    # Property: Handler must return success
    assert response['statusCode'] == 200, \
        f"Handler should return 200, got {response['statusCode']}"
    
    # Property: Response must indicate alarm was generated
    body = json.loads(response['body'])
    assert body['success'] is True, "Response should indicate success"
    assert body['alarm_generated'] is True, \
        "Response should indicate alarm was generated"
    
    # Property: Alarm must be stored in DynamoDB
    assert mock_alarms_table.put_item.call_count == 1, \
        f"Alarm should be stored once, put_item called {mock_alarms_table.put_item.call_count} times"
    
    # Property: Stored alarm must have all required fields
    call_args = mock_alarms_table.put_item.call_args
    stored_item = call_args.kwargs['Item']
    
    required_fields = [
        'alarm_id', 'variable_id', 'severity', 'status',
        'value', 'threshold', 'created_at'
    ]
    
    for field in required_fields:
        assert field in stored_item, f"Stored alarm missing required field: {field}"
    
    # Property: Stored alarm must have correct values
    assert stored_item['variable_id'] == variable_id
    assert stored_item['area'] == area
    assert stored_item['value'] == value
    assert stored_item['status'] == 'active'
    assert stored_item['threshold'] == alarm_high
    assert stored_item['threshold_type'] == 'high'


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
